export enum ProjectStatus {
  SEEKING_FUNDING = 'SEEKING_FUNDING',
  FUNDED_ORDER_PLACED = 'FUNDED_ORDER_PLACED',
  FUNDED_MACHINE_SHIPPED = 'FUNDED_MACHINE_SHIPPED',
  FUNDED_INSTALLATION_PHASE = 'FUNDED_INSTALLATION_PHASE',
  OPERATIONAL = 'OPERATIONAL',
} 